<a href="https://colab.research.google.com/github/tatyanalitvin/python_for_ds_tasks/blob/dev/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sympy import Matrix
from IPython.display import display, Math

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
# Генерація випадкових чисел з модулем random.uniform.
vector = np.random.uniform(size=10)

print(f"""
Vector:
{vector}

Type:
{type(vector)}

Shape:
{vector.shape}
"""
)


Vector: 
[0.82732081 0.6106558  0.47596477 0.48539119 0.34640736 0.55961525
 0.33668293 0.99291521 0.91384193 0.71164046]

Type:
<class 'numpy.ndarray'>
      
Shape: 
(10,)



In [3]:
# Створення вектора з допомогою метода numpy np.random.rand
vector = np.random.rand(10, )
print(f"""
Vector:
{vector}

Type:
{type(vector)}

Shape:
{vector.shape}
"""
)


Vector: 
[0.98782698 0.74137793 0.27962779 0.07390986 0.76389884 0.92482086
 0.66548243 0.25820476 0.94378137 0.75970358]

Type:
<class 'numpy.ndarray'>
      
Shape: 
(10,)



In [4]:
# Створіть матрицю matrix типу numpy.array розмірності 3x3 з наступними значеннями
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
  ])

print(f"""
Vector:
{matrix}

Type:
{type(matrix)}

Shape:
{matrix.shape}
"""
)


Vector: 
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Type:
<class 'numpy.ndarray'>
      
Shape: 
(3, 3)




### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [5]:
# Додайте до кожного значення вектора vector число 10
# і округліть кожне значення до 2 знаків після коми без використання циклів.

print(f"""
Original vector rounded:
{vector.round(decimals=2)}

vector+10 rounded:
{(vector + 10).round(decimals=2)}
"""
)


Original vector rounded: 
[0.99 0.74 0.28 0.07 0.76 0.92 0.67 0.26 0.94 0.76]
      
vector+10 rounded: 
[10.99 10.74 10.28 10.07 10.76 10.92 10.67 10.26 10.94 10.76]



In [6]:
# Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
matrix_multiplied_by_2 = matrix*2
display(Matrix(matrix), Math('\\times'), 2, Math('='), Matrix(matrix_multiplied_by_2))

Matrix([
[11, 14, 17],
[20, 23, 26],
[29, 32, 35]])

<IPython.core.display.Math object>

2

<IPython.core.display.Math object>

Matrix([
[22, 28, 34],
[40, 46, 52],
[58, 64, 70]])

In [7]:
# Створіть новий вектор, який містить квадрат кожного vector без циклів.
vector_squared = vector**2

print(f"""
Original vector rounded:
{vector}

Vector+10 rounded:
{vector_squared}
"""
)


Original vector rounded: 
[0.98782698 0.74137793 0.27962779 0.07390986 0.76389884 0.92482086
 0.66548243 0.25820476 0.94378137 0.75970358]
      
Vector+10 rounded: 
[0.97580214 0.54964123 0.0781917  0.00546267 0.58354144 0.85529363
 0.44286686 0.0666697  0.89072327 0.57714953]




### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [8]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [9]:
# Задані дві матриці A і Bрозмірностями 3x2 та 2х3.
# Виконайте їхнє множення, щоб отримати матрицю 2x2.
# Виведіть результуючу матрицю result_matrix на екран.
result_matrix = np.dot(B, A)
display(Matrix(A), Math('\\times'), Matrix(B), Math('='), Matrix(result_matrix))

Matrix([
[0.18, 0.53],
[0.75, 0.47],
[0.35, 0.21]])

<IPython.core.display.Math object>

Matrix([
[0.17, 0.58, 0.75],
[0.38, 0.11, 0.15]])

<IPython.core.display.Math object>

Matrix([
[0.7281, 0.5202],
[0.2034, 0.2846]])

In [10]:
# Заданий вектор C розмірністю 2х1.
# Подумайте спочатку, яку розмірність Ви отрмаєте,
# коли домножите result_matrix на вектор C і який результат буде.
# А потім виконайте множення і виведіть результат на екран.
display(Matrix(result_matrix), Math('\\times'), Matrix(C), Math('='), Matrix(np.dot(result_matrix, C)))

Matrix([
[0.7281, 0.5202],
[0.2034, 0.2846]])

<IPython.core.display.Math object>

Matrix([
[0],
[1]])

<IPython.core.display.Math object>

Matrix([
[0.5202],
[0.2846]])

In [11]:
# Задана матриця D розмірністю 2х2.
# Подумайте спочатку, яку розмірність Ви отрмаєте,
# коли домножите result_matrix на матрицю D і який результат буде.
# А потім виконайте множення і виведіть результат на екран.

In [12]:
display(Matrix(result_matrix), Math('\\times'), Matrix(D), Math('='), Matrix(np.dot(result_matrix, D)))

Matrix([
[0.7281, 0.5202],
[0.2034, 0.2846]])

<IPython.core.display.Math object>

Matrix([
[0, 1],
[1, 0]])

<IPython.core.display.Math object>

Matrix([
[0.5202, 0.7281],
[0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [13]:
# Транспонуйте result_matrix.
print("Оригінальна result_matrix:")
display(Matrix(result_matrix))

print("\nТранспонована result_matrix:")
display(Matrix(result_matrix.T))


Оригінальна result_matrix:


Matrix([
[0.7281, 0.5202],
[0.2034, 0.2846]])


Транспонована result_matrix:


Matrix([
[0.7281, 0.2034],
[0.5202, 0.2846]])

In [14]:
# Зробіть транспонування вектора vector і виведіть форму нової структури.
# Чи бачите ви зміну?
print(f"""
Vector:
{vector}
Shape:
{vector.shape}

Vector T:
{vector.T}
Shape:
{vector.T.shape}
"""
)


Vector: 
[0.98782698 0.74137793 0.27962779 0.07390986 0.76389884 0.92482086
 0.66548243 0.25820476 0.94378137 0.75970358]
Shape: 
(10,)
      
Vector T: 
[0.98782698 0.74137793 0.27962779 0.07390986 0.76389884 0.92482086
 0.66548243 0.25820476 0.94378137 0.75970358]
Shape: 
(10,)



In [15]:
# Використайте операцію numpy.expand_dims над вектором vector з аргументом axis=1.
# Запишіть отриманий результат в змінну column_vector і виведіть на екран.
# Порівняйте з vector.
column_vector = np.expand_dims(vector, axis=1)
print(f"""
Vector:
{vector}
Shape:
{vector.shape}

Vector with expanded dimensions:
{column_vector}
Shape:
{column_vector.shape}
"""
)



Vector: 
[0.98782698 0.74137793 0.27962779 0.07390986 0.76389884 0.92482086
 0.66548243 0.25820476 0.94378137 0.75970358]
Shape: 
(10,)
      
Vector with expanded dimensions: 
[[0.98782698]
 [0.74137793]
 [0.27962779]
 [0.07390986]
 [0.76389884]
 [0.92482086]
 [0.66548243]
 [0.25820476]
 [0.94378137]
 [0.75970358]]
Shape: 
(10, 1)



In [16]:
# Зробіть транспонування column_vector,
# виведіть результат на екран разом з розмірностями отриманої структури.
print(f"""
column_vector:
{column_vector}
Shape:
{column_vector.shape}

column_vector T:
{column_vector.T}
Shape:
{column_vector.T.shape}
"""
)


column_vector: 
[[0.98782698]
 [0.74137793]
 [0.27962779]
 [0.07390986]
 [0.76389884]
 [0.92482086]
 [0.66548243]
 [0.25820476]
 [0.94378137]
 [0.75970358]]
Shape: 
(10, 1)
      
column_vector T: 
[[0.98782698 0.74137793 0.27962779 0.07390986 0.76389884 0.92482086
  0.66548243 0.25820476 0.94378137 0.75970358]]
Shape: 
(1, 10)

